net stop "Application Layer Gateway Service" 
net stop "Automatic Updates" 
net stop "Background Intelligent Transfer Service" 
net stop "Bluetooth Support Service" 
net stop "COM+ Event System" 
net stop "Computer Browser" 
net stop "Cryptographic Services" 
net stop "HID Input Service" 
net stop "IPSEC Services" 
net stop "Logical Disk Manager" 
net stop "Network Location Awareness (NLA)" 
net stop "OneTouch 4.0 Monitor" 
net stop "Print Spooler" 
net stop "Remote Registry" 
net stop "Server" 
net stop "Shell Hardware Detection" 
net stop "System Event Notification" 
net stop "Themes" 
net stop "VMware Authorization Service" 
net stop "VMware DHCP Service" 
net stop "VMware NAT Service" 
net stop "Windows Audio" 
net stop "Windows Driver Foundation - User-mode Driver Framework" 
net stop "Windows Firewall/Internet Connection Sharing (ICS)" 
net stop "Windows Image Acquisition (WIA)" 
net stop "Windows Management Instrumentation" 
net stop "Windows Search" 
net stop "Windows Time" 
net stop "Wireless Zero Configuration" 
net stop "Workstation" 
